sudo: required

services:
        - docker

before_install:
        - docker build -t arajputdocker/react-test -f ./client/Dockerfile.dev ./client


script:
        - docker run -e CI=true arajputdocker/react-test npm test

after_success:
        - docker build -t arajputdocker/multi-client ./client
        - docker build -t arajputdocker/multi-nginx ./nginx
        - docker build -t arajputdocker/multi-server ./server
        - docker build -t arajputdocker/multi-worker ./worker
      

        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

        
        - docker push arajputkdocker/multi-client
        - docker push arajputdocker/multi-nginx
        - docker push arajputdocker/multi-server
        - docker push arajputdocker/multi-worker


